/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_nnproject_tls_SSLSocket */

#ifndef _Included_ru_nnproject_tls_SSLSocket
#define _Included_ru_nnproject_tls_SSLSocket
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_nnproject_tls_SSLSocket
 * Method:    _new
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ru_nnproject_tls_SSLSocket__1new
  (JNIEnv *, jobject);

/*
 * Class:     ru_nnproject_tls_SSLSocket
 * Method:    _set
 * Signature: (ILjava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_ru_nnproject_tls_SSLSocket__1set
  (JNIEnv *, jobject, jint, jstring, jstring, jint);

/*
 * Class:     ru_nnproject_tls_SSLSocket
 * Method:    _initSsl
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ru_nnproject_tls_SSLSocket__1initSsl
  (JNIEnv *, jobject, jint);

/*
 * Class:     ru_nnproject_tls_SSLSocket
 * Method:    _connect
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ru_nnproject_tls_SSLSocket__1connect
  (JNIEnv *, jobject, jint);

/*
 * Class:     ru_nnproject_tls_SSLSocket
 * Method:    _handshake
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ru_nnproject_tls_SSLSocket__1handshake
  (JNIEnv *, jobject, jint);

/*
 * Class:     ru_nnproject_tls_SSLSocket
 * Method:    _verify
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ru_nnproject_tls_SSLSocket__1verify
  (JNIEnv *, jobject, jint);
/*
 * Class:     ru_nnproject_tls_SSLSocket
 * Method:    _localPort
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ru_nnproject_tls_SSLSocket__1localPort
  (JNIEnv *, jobject, jint);

/*
 * Class:     ru_nnproject_tls_SSLSocket
 * Method:    _read
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_ru_nnproject_tls_SSLSocket__1read
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     ru_nnproject_tls_SSLSocket
 * Method:    _write
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_ru_nnproject_tls_SSLSocket__1write
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     ru_nnproject_tls_SSLSocket
 * Method:    _closeSsl
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ru_nnproject_tls_SSLSocket__1closeSsl
  (JNIEnv *, jobject, jint);

/*
 * Class:     ru_nnproject_tls_SSLSocket
 * Method:    _closeConnection
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ru_nnproject_tls_SSLSocket__1closeConnection
  (JNIEnv *, jobject, jint);

/*
 * Class:     ru_nnproject_tls_SSLSocket
 * Method:    _destruct
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ru_nnproject_tls_SSLSocket__1destruct
  (JNIEnv *, jobject, jint);

/*
 * Class:     ru_nnproject_tls_SSLSocket
 * Method:    _initLibrary
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ru_nnproject_tls_SSLSocket__1initLibrary
  (JNIEnv *, jclass);

/*
 * Class:     ru_nnproject_tls_SSLSocket
 * Method:    _freeLibrary
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ru_nnproject_tls_SSLSocket__1freeLibrary
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
